BW-18 Countdown implementieren
Rytrox/Bedwars pull request #10
Opened 2021-09-17 20:41 UTC by kaigoe

2021-09-17 20:54 UTC, Timeout-Timo requested changes

2021-09-17 20:54 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/phase/PhaseManager.java
> +
Die leere Zeile ist eigentlich nicht notwendig...
Man sieht ja schon gut genug, dass das ein Methodenkörper ist, oder findest du nicht?

2021-09-17 20:54 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/utils/Countdown.java
> +    private int minPlayerSize = 1;
Zu myInt: Was soll diese Variable aussagen, du verwendest die halt nirgendwo.
Zu minPlayerSize: Das hättest du vielleicht einfacher von der Config lesen können. Dann hätten wir nicht das Problem mit dem fixen Player 1.

2021-09-17 20:54 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/utils/Countdown.java
> +        if(playerOnlineSize > 1) {
```suggestion
        if(playerOnlineSize > this.minPlayerSize) {
```

2021-09-17 20:54 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/utils/Countdown.java
> +                        player.sendTitle("START","BEDWARS");
Vielleicht solltest du hier deinen Task stoppen. Das ist ein unnötiger Overhead, wenn der Scheduler für den Countdown immernoch läuft, obwohl der Countdown nicht mehr benötigt wird.

Dann kannst du dir auch die If-Überprüfung in Zeile 31 sparen also if(timer.get() >= 0)

2021-09-17 21:24 UTC, Timeout-Timo requested changes

2021-09-17 21:24 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/utils/Countdown.java
> +                timer.set(timer.get() - 1);
```suggestion
                int currentTime = timer.decrementAndGet();
                if(currentTime > 0) {
                    Bukkit.getOnlinePlayers().forEach((player) -> player.sendTitle(String.valueOf(currentTime), "SECONDS LEFT"));
                } else {
                    Bukkit.getOnlinePlayers().forEach((player) -> player.sendTitle("START", "BEDWARS"));
                    task.cancel();
                }
```
AtomicInteger hat sogar eine exklusive Methode, die die Zahl um 1 runterzählt und dann die aktuelle Zahl als int zurückgibt. Das wäre hier doch total praktisch!

Den Task solltest du nicht in der ForEach canceln...
Der würde sonst die Cancel Methode für jeden Spieler, der online ist, einmal aufrufen. Das wäre zu viel

2021-09-17 22:22 UTC, Timeout-Timo approved these changes

2021-09-18 10:12 UTC, Sether701 approved these changes

2021-09-18 10:13 UTC, merged