BW-8 Map-Setup
Rytrox/Bedwars pull request #14
Opened 2021-10-09 14:33 UTC by Asedem

2021-10-09 15:31 UTC, Timeout-Timo requested changes

2021-10-09 15:31 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/commands/BedwarsMapCommand.java
> +                if ("modify".equals(args[0])) {
Die beiden ifs können gemergt werden mit &&

2021-10-09 15:31 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/commands/BedwarsMapCommand.java
> +                                if (main.getMapUtils().getMapsInEdit().get(args[1]).getTeams()
Versuch hier das Optional zu nutzen. Zweimal suchen ist unnötig im Vergleich dazu zu suchen mit einem Optional und es direkt zu getten wenn es da ist mit Optional#ifPresent

2021-10-09 15:31 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/commands/BedwarsMapCommand.java
> +                                if (main.getMapUtils().getMapsInEdit().get(args[1]).getTeams()
Hier selbes Prinzip mit der Zweifachsuche

2021-10-09 15:31 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/commands/BedwarsMapCommand.java
> +                                if (main.getMapUtils().getMapsInEdit().get(args[1]).getTeams()
Hier auch mit Zweifachsuche

2021-10-09 15:31 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/commands/BedwarsMapCommand.java
> +                        if (main.getMapUtils().getMapsInEdit().get(args[1]).getTeams()
Und hier auch mit der Zweifachsuche

2021-10-09 15:31 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/database/repository/MapRepository.java
> +                .map(Map::getName)
Statt ganze Objekte zu parsen, kannst du hier auch findIds verwenden.

https://ebean.io/docs/query/findIds

2021-10-09 19:00 UTC, Sether701 approved these changes
ja, passt im Großen und Ganzen. Meinen Vorschlag musst du nicht umsetzen, ist nur etwas das man machen könnte. Wenn du die Sachen von Timo durch hast, hab ich nichts weiter zu bemängeln

2021-10-10 08:30 UTC, Timeout-Timo requested changes

2021-10-10 08:30 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/commands/BedwarsMapCommand.java
> +                                                    .ifPresent(team -> main.getMapUtils().getMapsInEdit().get(args[1]).removeTeam(team));
Hier ist immernoch die doppelte Suche

2021-10-10 08:30 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/map/MapUtils.java
> +        return mapsInEdit.put(name, new Map(name));
https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html#put-K-V-

Sicher, dass du das damit meinst? Du würdest hier einfach immer null returnen...

2021-10-10 08:31 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/map/MapUtils.java
> +        return map;
Nein, die alten und neuen Ausdrücke sind nicht äquivalent. 
Map#put returnt den Wert, der vorher mit dem Key in der Map war, sonst null.

2021-10-10 18:29 UTC, Timeout-Timo approved these changes

2021-10-10 18:30 UTC, merged