BW-5: Created TopTenBoard
Rytrox/Bedwars pull request #16
Opened 2021-11-07 23:07 UTC by Asedem

2021-11-08 08:03 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/database/repository/PlayerStatisticsRepository.java
> +                .orderBy("wins")
Die Stats basieren nur auf der Anzahl der Wins? Nicht n bissl langweilig? xd

2021-11-08 08:05 UTC, Sether701 approved these changes

2021-11-08 11:17 UTC, Asedem commented on src/main/java/de/rytrox/bedwars/database/repository/PlayerStatisticsRepository.java
> +                .orderBy("wins")
Was schlägst du denn vor, ich als Kriterium nehmen soll, um den Platz in der Liste zu ermitteln?

2021-11-08 14:07 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/database/repository/PlayerStatisticsRepository.java
> +                .orderBy("wins")
Naja, man könnte auch noch die Anzahl der Kills, Anzahl zerstörter Betten usw. mit reinnehmen. Oder andersrum, viele Tode und Bettverluste bestrafen. Das sind zwar Sachen, die du glaub momentan nicht trackst, aber könnte man ja machen. Das könnte man dann unsichtbar machen, oder in Form eines "Scores" den Spielern einsehbar machen

2021-11-08 15:18 UTC, Timeout-Timo requested changes

2021-11-08 15:18 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/Bedwars.java
> +                TopTenSigns.class
Das Wording von der Entity verwirrt mich was. Ist das ein oder mehrere Signs?

2021-11-08 15:19 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/database/repository/PlayerStatisticsRepository.java
> +                .orderBy("wins")
Mit dem Score wäre das auch ne echt nice Idee.
Aber wenn ihr meint, das Wins reichen. Was meinst du denn hier @kaigoe ?

2021-11-08 15:34 UTC, Asedem commented on src/main/java/de/rytrox/bedwars/database/repository/PlayerStatisticsRepository.java
> +                .orderBy("wins")
Ich habe mir überlegt, dass man beim erstellen der Schilder in einer weiteren Zeile noch sagen kann, dass man nach wins, Kills, deaths, oder Games gelistet haben möchte. Oder man schreibt dann auf das Schild z.B. "all" und dann wird halt eine Wertung aus allem, wie Sether es meinte genommen um die Platzierung zu bestimmen.

2021-11-09 08:29 UTC, Timeout-Timo approved these changes

2021-11-09 08:30 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/database/repository/PlayerStatisticsRepository.java
> +                .orderBy("wins")
Dann müsstest du die Methoden aber auch in SQL bereitstellen.
Ebean hat eine Query-Funktion. Gegebenenfalls musst du die verwenden (also einen Raw-Query)

2021-11-10 16:09 UTC, Sether701 commented
@Asedem möchtest du denn dann noch Änderungen am Ranking machen? Wenn nicht, kannst du die conversation oben auf resolved setzen und wir könnten mergen

2021-11-10 21:20 UTC, Asedem commented
Ich bin soweit zufrieden. Ich bin mir mit dem Code aber nicht ganz sicher. wenigsten funktioninert er. Wenn von euch aus alles in Ordung ist könnt ihr jetzt mergen.

2021-11-10 21:32 UTC, Timeout-Timo requested changes

2021-11-10 21:32 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/database/entity/TopTenSign.java
> +    String sorted;
Also für sowas kannst du gerne ein Enum erstellen

2021-11-13 19:53 UTC, Timeout-Timo approved these changes

2021-11-13 19:53 UTC, merged