BW-24 Special Item Rettungsplattform
Rytrox/Bedwars pull request #17
Opened 2021-11-08 19:45 UTC by kaigoe

2021-11-09 08:27 UTC, Timeout-Timo requested changes

2021-11-09 08:27 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/items/Rettungsplatform.java
> +
Technisch wäre das ganze viel einfacher zu handhaben:

Wie wäre es, wenn du eine Liste / ein Set erstellst mit allen Locations, die du gesetzt hast und die durchläufst du am Ende und zerstörst die Blöcke an der Location, wenn die Purple Glass sind?

2021-11-09 08:28 UTC, Timeout-Timo commented
Generell sollten die Special-Items am Ende in der IngamePhase registriert werden, nicht in der Main. Wir brauchen die Listener doch nicht in jeder Phase

2021-11-23 19:47 UTC, Timeout-Timo requested changes

2021-11-23 19:47 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/items/Rettungsplatform.java
> +                    }
Statt das hier zu wiederholen, kannst du hier eine Liste erstellen mit Blöcken, die du verändert hast und dann diese Koordinaten neu setzen? 

Wir können uns dafür am Donnerstag zusammen hinsetzen

2021-11-23 19:47 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/items/Rettungsplatform.java
> +                player.sendMessage("lol");
```suggestion
```

Debug-Message kann hier entfernt werden

2021-11-25 17:29 UTC, Timeout-Timo approved these changes

2021-11-25 17:35 UTC, Sether701 approved these changes

2021-11-25 17:36 UTC, merged