BW-26 Special Item Bridge
Rytrox/Bedwars pull request #19
Opened 2021-11-08 23:13 UTC by kaigoe

2021-11-09 08:22 UTC, Timeout-Timo requested changes

2021-11-09 08:22 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/items/Bridge.java
> +                float Yaw = player.getLocation().getYaw();
Variablen sind klein zu schreiben

2021-11-09 08:22 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/items/Bridge.java
> +                    player.sendMessage("z+");
Debug-Message entfernen

2021-11-09 08:22 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/items/Bridge.java
> +                    player.sendMessage("x-");
Debug-Message entfernen

2021-11-09 08:22 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/items/Bridge.java
> +                    player.sendMessage("z-");
Debug-Message entfernen

2021-11-09 08:22 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/items/Bridge.java
> +                    player.sendMessage("x+");
Debug-Message entfernen

2021-11-13 19:51 UTC, Timeout-Timo approved these changes

2021-11-13 19:54 UTC, Sether701 approved these changes

2021-11-13 19:54 UTC, Sether701 commented
@kaigoe noch merge konflikt lösen, dann kann gemerget werden

2021-11-25 17:31 UTC, Sether701 approved these changes

2021-11-25 17:34 UTC, merged