BW-28 Welt darf während Lobbyphase nicht verändert werden
Rytrox/Bedwars pull request #21
Opened 2021-12-12 16:02 UTC by Asedem

2021-12-13 07:28 UTC, Sether701 requested changes

2021-12-13 07:28 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/listeners/LobbyBreakPlaceListener.java
> +    }
Es gibt es da noch ein paar weitere Events zu beachten. Beispielsweise das PlayerInteract Event für Redstone, Türen, Chests, Felder, etc. oder das BlockIgniteEvent für TNT, oder das BlockGrowEvent für Pflanzen usw.

2021-12-13 09:42 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/LobbyBreakPlaceListener.java
> +    }
Noch schnell anpassen und dann kann das gemergt werden

2021-12-13 21:56 UTC, Timeout-Timo requested changes
Bitte fehlende Events noch berücksichtigen

2021-12-14 17:36 UTC, Sether701 approved these changes

2021-12-14 17:36 UTC, Timeout-Timo approved these changes

2021-12-14 17:37 UTC, merged