story/BW-32
Rytrox/Bedwars pull request #22
Opened 2021-12-15 00:07 UTC by kaigoe

2021-12-15 08:05 UTC, Timeout-Timo requested changes
Also ist die Idee hier jetzt, dass wir uns zufällig irgendeine Map aus der Datenbank ziehen und die dann da in den MapLoader legen?

Woher kannst du dir sicher sein, dass der Map-Ordner existiert? Wir könnten Datensätze in der Datenbank haben, die für andere Server da sind.
Vielleicht sollten wir das umgehen mit einer Methode, die als Parameter nur die Elemente selektiert, von denen wir wissen, dass der Ordner richtig hinterlegt ist. 
Ich denke hier an WHERE worldname IN ('world1', 'world2', ..., 'worldn')

2021-12-15 08:05 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/map/MapLoader.java
> +    public Map getMap(){return map;};
```suggestion
    public Map getMap(){
        return map;
    };
```

2021-12-15 17:16 UTC, Sether701 requested changes

2021-12-15 17:16 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/map/MapLoader.java
> +        });
Nimm dir doch erst die Liste vom #findAllMaps, shuffle die und öffne dann den Stream
Du machst Liste -> Stream -> Liste -> Stream. Das hatt doch keinen Sinn xD

2021-12-16 07:45 UTC, kaigoe commented
> Also ist die Idee hier jetzt, dass wir uns zufällig irgendeine Map aus der Datenbank ziehen und die dann da in den MapLoader legen?
> 
> Woher kannst du dir sicher sein, dass der Map-Ordner existiert? Wir könnten Datensätze in der Datenbank haben, die für andere Server da sind. Vielleicht sollten wir das umgehen mit einer Methode, die als Parameter nur die Elemente selektiert, von denen wir wissen, dass der Ordner richtig hinterlegt ist. Ich denke hier an WHERE worldname IN ('world1', 'world2', ..., 'worldn')

ich weiß irgendwie gerade nicht, was du meinst

2021-12-16 13:56 UTC, Timeout-Timo commented
> > Also ist die Idee hier jetzt, dass wir uns zufällig irgendeine Map aus der Datenbank ziehen und die dann da in den MapLoader legen?
> > Woher kannst du dir sicher sein, dass der Map-Ordner existiert? Wir könnten Datensätze in der Datenbank haben, die für andere Server da sind. Vielleicht sollten wir das umgehen mit einer Methode, die als Parameter nur die Elemente selektiert, von denen wir wissen, dass der Ordner richtig hinterlegt ist. Ich denke hier an WHERE worldname IN ('world1', 'world2', ..., 'worldn')
> 
> ich weiß irgendwie gerade nicht, was du meinst

Angenommen ich habe zwei Server, die über dieselbe Datenbank laufen oder ich habe in meinder Datenbank eine Mapkonfiguration, deren Welt ich nicht laden kann. Deine Abfrage würde nun diese Anfrage bearbeiten und kann die Welt dann nicht laden. Das würde zu einem kritischen Fehler führen. Sich alle Maps von der Datenbank zu holen wäre also keine gute Idee. Besser wäre es hier, dass du nur die Maps aus der Datenbank ziehst, deren Weltdaten du auch im Weltordner hast. Dann könnte das Problem auch nicht auftreten

2021-12-19 17:33 UTC, Timeout-Timo approved these changes

2021-12-19 17:34 UTC, Sether701 approved these changes

2021-12-19 17:34 UTC, merged