BW-30 Bed Break
Rytrox/Bedwars pull request #24
Opened 2021-12-22 21:41 UTC by Asedem

Ich bin mir nicht sicher, ob das so funktioniert, oder ob ich da nen dicken Denkfehler drinnen habe.

2021-12-23 17:46 UTC, Timeout-Timo requested changes

2021-12-23 17:46 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/BedBreakListener.java
> +                    });
Teste den Code einmal auf dem Server durch. So sieht das in Ordnung aus. Gib mir da mal Rückmeldung!

2021-12-23 17:46 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/team/Team.java
> +    }
Das muss hier wohl nicht sein, oder?
Bitte verschieb entweder das Objekt in die passende GamePhase oder erstell eine Klasse und erb von dieser

2021-12-23 17:46 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/team/TeamManager.java
> +    }
Das könntest du auch auslagern.
Ich sehe nicht gerne Phasenspezifische Methoden in einer phasenunabhängiger Klasse

2021-12-26 21:20 UTC, Sether701 approved these changes

2021-12-26 21:20 UTC, Timeout-Timo requested changes

2021-12-26 21:20 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/BedBreakListener.java
> +            else location = (((Block) bed).getRelative(bed.getFacing().getOppositeFace())).getLocation();
```suggestion
            location = bed.isHeadOfBed() ? (((Block) bed).getRelative(bed.getFacing())).getLocation() : 
                (((Block) bed).getRelative(bed.getFacing().getOppositeFace())).getLocation();
```

2021-12-30 22:52 UTC, Timeout-Timo requested changes

2021-12-30 22:52 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/database/entity/Team.java
> +    public Set<Player> getMembers() {
```suggestion
    @NotNull
    public Set<Player> getMembers() {
```

2021-12-30 22:52 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/database/entity/Team.java
> +    public boolean addMember(Player member) {
```suggestion
    public boolean addMember(@NotNull Player member) {
```

2021-12-30 22:52 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/database/entity/Team.java
> +    public boolean removeMember(Player member) {
```suggestion
    public boolean removeMember(@NotNull Player member) {
```

2021-12-30 22:52 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/database/enums/TeamItem.java
> +    DARK_RED(ChatColor.DARK_RED, Material.RED_WOOL);
Hier fehlen die anderen States

2021-12-30 22:52 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/BedBreakListener.java
> +    public BedBreakListener(Map map, TeamManager teamManager) {
```suggestion
    public BedBreakListener(@NotNull Map map, @NotNullTeamManager teamManager) {
```

2021-12-30 22:52 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/map/MapLoader.java
> +    public MapLoader(Bedwars main, TeamManager teamManager){
```suggestion
    public MapLoader(@NotNull Bedwars main, @NotNull TeamManager teamManager){
```

2021-12-30 23:10 UTC, Timeout-Timo approved these changes

2021-12-30 23:10 UTC, merged