BW-29 Player Kills / Deaths
Rytrox/Bedwars pull request #26
Opened 2021-12-31 14:11 UTC by Asedem

Spieler erhalten nur noch Schaden, wenn sie und der Schaden machende Spieler einem Team angehört. Wenn ein Spieler Stirbt werden seinen Statistiken einen Tod hinzugefügt und wenn es einen Killer gibt wird ihm ein Kill hinzugefügt. Die Nachricht erscheint je nach normalem Kill oder final kill anders und in den Farben von dem Team des getöteten Spielers im Chat.

2021-12-31 14:27 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/listeners/KillDeathListener.java
> +                .ifPresent(playerStatistic -> playerStatistic.setDeaths(playerStatistic.getDeaths() + 1)));
fehlt hier nicht das speichern?

2021-12-31 14:33 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/listeners/KillDeathListener.java
> +        if (damageCause.equals(EntityDamageEvent.DamageCause.ENTITY_ATTACK)) {
wozu die damage cause überprüfen? Wurde der Spieler nicht von einem Spieler getötet, dürfte doch der Killer null sein, oder net?

2021-12-31 14:35 UTC, Asedem commented on src/main/java/de/rytrox/bedwars/listeners/KillDeathListener.java
> +        if (damageCause.equals(EntityDamageEvent.DamageCause.ENTITY_ATTACK)) {
Ich meine, dass das der Spieler genommen wird, der de letzte Killer war. Also evtl. von dem Kill davor...

2021-12-31 14:36 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/listeners/KillDeathListener.java
> +        if (damageCause.equals(EntityDamageEvent.DamageCause.ENTITY_ATTACK)) {
hast du das mal ausprobiert?

2021-12-31 14:37 UTC, Asedem commented on src/main/java/de/rytrox/bedwars/listeners/KillDeathListener.java
> +        if (damageCause.equals(EntityDamageEvent.DamageCause.ENTITY_ATTACK)) {
Habe ich noch nicht. Mache ich dann gleich.

2021-12-31 14:39 UTC, Timeout-Timo requested changes

2021-12-31 14:39 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/KillDeathListener.java
> +        if (damageCause.equals(EntityDamageEvent.DamageCause.ENTITY_ATTACK)) {
Grundsätzlich ja. Die Überprüfung muss sogar weg, weil wenn ein Spieler durch einen anderen Spieler ins Void fliegt, wird deswegen der Kill nicht addiert

2021-12-31 14:39 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/KillDeathListener.java
> +        if (playerTeam.equals(damagerTeam)) event.setCancelled(true);
Merge die beiden Statements. Das macht so keinen Sinn das explizit zu schreiben

2021-12-31 15:24 UTC, Timeout-Timo approved these changes

2021-12-31 15:26 UTC, Timeout-Timo requested changes

2021-12-31 15:26 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/KillDeathListener.java
> +}
Was ist denn hier mit Projektilen wie Pfeile? Das berücksichtigst du garnicht

2021-12-31 15:27 UTC, Sether701 approved these changes

2021-12-31 16:11 UTC, Timeout-Timo approved these changes

2021-12-31 16:12 UTC, Sether701 approved these changes

2022-01-01 12:42 UTC, Asedem commented
Ist hier für mich noch irgendwas zu machen, oder habt ihr einfach noch nicht gemerged?

2022-01-01 15:37 UTC, merged

2022-01-01 15:38 UTC, Timeout-Timo commented
Einfach nur vergessen zu mergen 😅