BW-35: Fixed Color Reset at BedBreak Message & Added teamColor to Player
Rytrox/Bedwars pull request #27
Opened 2021-12-31 14:24 UTC by Asedem

2021-12-31 14:26 UTC, Sether701 approved these changes

2021-12-31 14:34 UTC, Timeout-Timo requested changes

2021-12-31 14:34 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/BedBreakListener.java
> +                                            " &fwurde von " + (playerTeam != null ? playerTeam.getColor() : "&f")
Kann hier das PlayerTeam tatsächlich null sein?

2021-12-31 15:34 UTC, Asedem commented on src/main/java/de/rytrox/bedwars/listeners/BedBreakListener.java
> +                                            " &fwurde von " + (playerTeam != null ? playerTeam.getColor() : "&f")
Ja, da wir voher nicht prüfen, ob der, der das Bett abgebaut hat auch in einem Team ist.

Ich könnte vorher noch eine Abfrage einbauen, dass man nur ein Bett abbauen kann, wenn man einem Team angehört, aber ich weiß nicht, ob das in dieses Ticket rein passt?

2021-12-31 16:13 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/BedBreakListener.java
> +                                            " &fwurde von " + (playerTeam != null ? playerTeam.getColor() : "&f")
Das macht technisch gesehen keinen Sinn...

Welcher Spieler ist denn in der IngamePhase in keinem Team? Das sind doch nur Spectator, die haben nichts zu zerstören

2022-01-01 19:23 UTC, Timeout-Timo approved these changes

2022-01-01 19:23 UTC, merged