BW-27 Lobby-Einrichtung
Rytrox/Bedwars pull request #38
Opened 2022-01-02 23:20 UTC by kaigoe

2022-01-03 07:49 UTC, Timeout-Timo requested changes

2022-01-03 07:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/BuildBreakListener.java
> +        pos2 = new Location(Bukkit.getWorld("world1"),map.getPos2().getX(),map.getPos2().getY(),map.getPos2().getZ());
1. Woher willst du dir sicher sein, dass die World nur "world1" heißt?
2. Wenn du eine Location kopieren willst, kannst du auch Location#clone verwenden

2022-01-03 07:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/utils/Area.java
> +    public boolean inArea(Location von, Location bis, Location current){
Hier bitte mit NotNull annotieren

2022-01-03 07:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/utils/Area.java
> +                current.getZ() <= Math.max(von.getZ(), bis.getZ()) && current.getZ() >= Math.min(von.getZ(), bis.getZ());
Du berücksichtigst hier nicht die Welten. Deine Locations können von 2 ganz unterschiedlichen Welten sprechen, trotzdem würden sie hier true liefern

2022-01-03 07:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/utils/LobbyArea.java
> +            event.getPlayer().teleport(new Location(event.getPlayer().getWorld(),0,50,0));
Woher kommen hier 0, 100, 50? Nicht jede Welt ist so aufgebaut wie deine Testwelt

2022-01-03 11:47 UTC, Sether701 requested changes

2022-01-03 11:47 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/utils/Area.java
> +    public boolean inArea(Location von, Location bis, Location current){
Wann sind wir zu deutschen Variablennamen gewechselt?

2022-01-03 11:47 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/utils/LobbyArea.java
> +        if(!new Area().inArea(new org.bukkit.Location(event.getPlayer().getWorld(),0,0,0),new org.bukkit.Location(event.getPlayer().getWorld(),100,100,100),event.getPlayer().getLocation())){
Wenn du die inArea-Funktion so verwenden willst, sollte die Methode statisch sein.

2022-01-03 15:11 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/utils/LobbyArea.java
> +        if(!new Area().inArea(new org.bukkit.Location(event.getPlayer().getWorld(),0,0,0),new org.bukkit.Location(event.getPlayer().getWorld(),100,100,100),event.getPlayer().getLocation())){
Man kann es so lösen, ich persönlich finde es nicht verwerflich. Aber zur Übersicht und Performance geb ich dir Recht

2022-01-04 17:43 UTC, Timeout-Timo approved these changes

2022-01-04 17:59 UTC, Timeout-Timo requested changes

2022-01-04 17:59 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/phase/phases/LobbyPhase.java
> +        this.lobbyArea = new LobbyArea(mapLoader.getMap());
Problem mit der Map...

Zu dem Zeitpunkt ist die Map null, du musst es anders herum implementieren.
Simon hat dasselbe Problem genauso gelöst. Er hat dafür seinen TeamManager in den Loader übergeben, das solltest du mit der LobbyArea auch machen

2022-01-05 13:25 UTC, Timeout-Timo approved these changes

2022-01-05 13:25 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/utils/LobbyArea.java
> +    public void setmap(Map map){
```suggestion
    public void setMap(@NotNull Map map){
```

2022-01-05 13:25 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/map/MapLoader.java
> +            lobbyArea.setmap(map);
```suggestion
            lobbyArea.setMap(map);
```

2022-01-05 13:26 UTC, Timeout-Timo commented
Hier muss noch der Merge-Request gelöst werden.

Bitte bei Commits nur schreiben, was du gemacht hast. "Timo's and Sether's changes" ist eine schlechte Commit-Message!

2022-01-07 08:49 UTC, Timeout-Timo requested changes

2022-01-07 08:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/Bedwars.java
> +
Wo kommt das denn her?

2022-01-07 08:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/Bedwars.java
>      }
Damit bin ich nicht einverstanden. Die Override Annotation soll da stehen bleiben.

2022-01-07 08:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/Bedwars.java
> -    @Override
Die Override-Annotation soll stehen bleiben

2022-01-07 08:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/Bedwars.java
>      public void saveConfig() {
```suggestion
    @Override
    public void saveConfig() {
```

2022-01-07 08:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/commands/BedwarsMapCommand.java
> +                main.getMapUtils().getMapsInEdit().get(mapName).setWorld(player.getWorld().getName());
Muss das denn hier im Command gesetzt werden? Warum kann das nicht in die Methode MapUtils#getOrCreateMap verlegt werden?

Dann benötigst du auch diesen Getter nicht mehr

2022-01-07 08:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/commands/LobbyCommand.java
> +                spawn = new Location(((Player)commandSender).getWorld(), 0.5D + (double)Integer.parseInt(strings[6]), 0.5D + (double)Integer.parseInt(strings[7]), 0.5D + (double)Integer.parseInt(stri
Also wirklich durchdacht ist dieser Command nicht.

Wenn du schon einen Spieler hast, der durch die Welt laufen kann und auch eine Location besitzt, warum musst du denn die Koordinaten trotzdem per Hand in den Befehl drücken?

Reicht es nicht einfach, wenn du die Spielerlocation nimmst und die als pos1 / pos2 / spawn nutzt?
Das würde dir so viel Arbeit sparen im TabComplete und im Command

2022-01-07 08:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/commands/LobbyCommand.java
> +        commandSender.sendMessage("error");
Ja, was für ein error? Das ist nicht ganz schlüssig...

2022-01-07 08:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/commands/LobbyCommand.java
> +
Siehe Kommentar oben mit den Spielerpositionen. Du hast dir hier richtig viel Arbeit gemacht, obwohl es einfacher und intuitiver geht

2022-01-07 08:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/database/entity/Map.java
> +    }
```suggestion
    @NotNull
    public String getWorld() {
        return world;
    }
```

2022-01-07 08:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/BedBreakListener.java
> +    public BedBreakListener(@NotNull Map map, @NotNull TeamManager teamManager, ScoreboardManager scoreboardManager) {
```suggestion
    public BedBreakListener(@NotNull Map map, @NotNull TeamManager teamManager, @NotNull ScoreboardManager scoreboardManager) {
```

2022-01-07 08:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/KillDeathListener.java
> +    public KillDeathListener(Bedwars main, TeamManager teamManager, ScoreboardManager scoreboardManager) {
```suggestion
    public KillDeathListener(Bedwars main, TeamManager teamManager, @NotNull ScoreboardManager scoreboardManager) {
```

2022-01-07 08:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/map/MapLoader.java
> +            List<String> worlds = (List)Bukkit.getServer().getWorlds().stream().map(World::getName).collect(Collectors.toList());
```suggestion
            List<String> worlds = Bukkit.getServer().getWorlds().stream()
                .map(World::getName)
                .collect(Collectors.toList());
```

2022-01-07 08:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/map/MapLoader.java
> +            });
```suggestion
            }, () -> System.out.println("No Map Found"));
```

2022-01-07 08:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/phase/phases/LobbyPhase.java
> -    @Override
JavaDoc beibehalten

2022-01-07 08:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/phase/phases/LobbyPhase.java
> -    @Override
JavaDoc beibehalten

2022-01-07 08:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/phase/phases/LobbyPhase.java
> -    @Override
JavaDoc beibehalten

2022-01-07 08:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/utils/LobbyArea.java
> +            new Area();
```suggestion
```

2022-01-07 08:49 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/utils/LobbyArea.java
> +            }
Das Move-Event an sich ist keine sonderlich gute Idee.

Das Problem mit dem MoveEvent ist, dass das in einer Sekunde bei 5 Spielern mindestens 1000 mal getriggert wird. Jede kleinste Bewegung lässt deinen Code ausführen.
Besser ist hier ein Scheduler, der jede Sekunde einmal läuft und deinen Code hier ausführt. Denk aber dran den nach der Lobbyphase dann wieder auszuschalten

2022-01-07 08:51 UTC, Timeout-Timo commented
Du hast nun erfahren, was ein Java-Decompiler macht. Allerdings haut er viele semantische Features durch die Optimierungen bzw. Komprimierung des Archivs einfach weg, darunter Override-Annotationen, JavaDocs und Kommentare. Sei da also bitte vorsichtig im Umgang. Du darfst dir gerne aus anderen Archiven Ideen und Code holen, das finde ich sogar sehr gut! Aber sei da beim Umsetzen ruhig etwas skeptischer 😅

2022-01-07 08:55 UTC, kaigoe commented
ich hab mir damit einfach eine stunde arbeit kaputt gemacht weil ich pnik hatte und auf got kraken irgendwie fünftausend sachen gamcht hab und jetzt sind alle commits kaputt xD

2022-01-07 08:58 UTC, Timeout-Timo commented
Sollen wir uns mal auf Discord treffen und schauen, was da alles hin ist?

2022-01-07 08:58 UTC, kaigoe commented
ja ich glaube wäre gut xD

2022-01-07 09:04 UTC, Sether701 commented
oh je, wat hat der kai da verbrochen

2022-01-08 11:00 UTC, Timeout-Timo requested changes
Mir fehlt hier noch eine Sache.
Wo lädst du den Spawnpoint der Spieler und sagst denen, dass die sich an diesem Spawnpoint einloggen?

Die Area liest du ja und du überprüfst darauf, aber was ist beim Login?

2022-01-10 14:47 UTC, kaigoe commented
das ist doch komplett egal, weil die sowieso dahinteleportiert werden, wenn die nicht in der area sind oder?

2022-01-10 18:34 UTC, Timeout-Timo commented
Theoretisch ja, allerdings wäre das beim Login trotzdem schön, wenn es direkt läuft, statt eine Sekunde verspätet, oder?

Es ist ja nur eine Zeile mehr

2022-01-11 17:07 UTC, Sether701 requested changes

2022-01-11 17:07 UTC, Sether701 commented on src/main/resources/plugin.yml
> +    usage: /lose
usage: /lose ohne dass "lose" als alias registriert ist?

2022-01-11 17:11 UTC, Sether701 requested changes

2022-01-11 17:11 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/commands/LobbyCommand.java
> +                    commandSender.sendMessage("spawn set");
im default fände ich eine Hilfestellung angemessener als einfach den Spawn anzunehmen

2022-01-11 17:59 UTC, Sether701 requested changes

2022-01-11 17:59 UTC, Sether701 commented on src/main/resources/plugin.yml
> +    usage: /lobbysetup [spwawn, pos1, pos2]
spwawn -> spawn

2022-01-11 17:59 UTC, Sether701 commented
Merge Konflikte beheben

2022-01-11 18:03 UTC, Timeout-Timo approved these changes

2022-01-11 18:03 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/PlayerSpawnListener.java
> +                main.getConfig().getDouble("lobby.spawn.Y"),
```suggestion
                main.getConfig().getDouble("lobby.spawn.y"),
```

2022-01-11 18:04 UTC, Sether701 requested changes

2022-01-11 18:04 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/listeners/PlayerSpawnListener.java
> +        ));
Was ist aus Yaw und Pitch geworden?

2022-01-11 18:05 UTC, Sether701 requested changes

2022-01-11 18:05 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/commands/LobbyCommand.java
> +            switch (args[0].toLowerCase(Locale.ROOT)) {
Fehlermeldung wenn keine Argumente

2022-01-11 21:26 UTC, Timeout-Timo requested changes

2022-01-11 21:26 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/PlayerSpawnListener.java
> +                main.getConfig().getDouble("lobby.spawn.z")
Hier in der Location fehlen noch Yaw und Pitch. Sonst sind ie ja umsonst gespeichert in der Config

2022-01-12 10:54 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/listeners/PlayerSpawnListener.java
> +                main.getConfig().getDouble("lobby.spawn.z")
hab ich doch schon angekreidet xD

2022-01-12 22:16 UTC, Timeout-Timo approved these changes

2022-01-12 22:17 UTC, merged