BW-11 Shop
Rytrox/Bedwars pull request #4
Opened 2021-07-17 13:52 UTC by Asedem

Das Shop System mit Villager, der keinen Schaden bekommen kann. Wenn man den Villager anklickt erscheint ein Menü, in welchem man sich die verschiedenen Spielitems kaufen kann. Der Preis und das Material ist mit NBT-Daten in den Items gespeichert. Den Villager kann man über eine Methode spawnen und über eine andere wieder umbringen. Wenn man ein Item im Shop Shift-Klickt, wird soviel davon gekauft, wie man das nötige Material im Inventar hat, mit Ausnahme von Items, welche sich nicht stacken lassen. Diese werden trotzdem nur 1 Mal gekauft.

2021-07-17 14:06 UTC, Sether701 requested changes

2021-07-17 14:06 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/listeners/VillagerDamageListener.java
> +                if(Objects.requireNonNull(villager.getCustomName()).equalsIgnoreCase(ChatColor.translateAlternateColorCodes('&', "&9&lShop"))) {
Sowas wie den Villager Namen solltest du dir irgendwo global als Konstante ablegen. Am besten wärs eigentlich das dann als Config-Wert zu haben

2021-07-17 14:06 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/utils/ShopUtils.java
> +                .filter((entity) -> Objects.requireNonNull(entity.getCustomName()).equalsIgnoreCase(ChatColor.translateAlternateColorCodes('&', "&9&lShop")))
Hier wieder der Villagername. Besser ist ne Konstante

2021-07-17 14:06 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/listeners/InvClickListener.java
> +        if(inventoryName.equalsIgnoreCase(ChatColor.translateAlternateColorCodes('&', "&9Shop | Rush"))
Hier bietet es sich an, mit startsWith zu arbeiten, wenn die Inventarnamen immer mit "Shop" anfangen

2021-07-17 14:06 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/listeners/InvClickListener.java
> +            if(ChatColor.translateAlternateColorCodes('&', "&b&lRush").equalsIgnoreCase(clickedItem.getItemMeta().getDisplayName()))
da könnte man mit nem switch rangehen, vor allem wenn es nachher variable kategorien geben sollte

2021-07-17 14:08 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/listeners/InvClickListener.java
> +            if(ChatColor.translateAlternateColorCodes('&', "&b&lRush").equalsIgnoreCase(clickedItem.getItemMeta().getDisplayName()))
wobei das eigentlich auch erstmal so reicht. das kannst du also ändern, musst du aber nicht zwingend

2021-07-17 14:14 UTC, Timeout-Timo requested changes
Kleiner Tipp: Benutz, bevor du dir sicher bist, das Plugin SonarLint und geh nochmal über deine Changes drüber. Du musst ja nicht alles umsetzen, was der vorschlägt, allerdings wäre es ratsam sich anzuhören, was er zu meckern hat, da dort viele Clean-Code Prinzipien eingearbeitet wurden. Linting ist für gute Softwareentwickler essentiell!

2021-07-17 14:14 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/utils/ShopUtils.java
> +    /*
Auskommentierter Code ist bitte zu entfernen

2021-07-17 14:14 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/InvClickListener.java
> +        if(inventoryName.equalsIgnoreCase(ChatColor.translateAlternateColorCodes('&', "&9Shop | Rush"))
Vielleicht könnte man hier einen Regex überprüfen, statt diese 4 OR-Cases zu überprüfen?

2021-07-17 14:14 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/utils/ShopUtils.java
> +public class ShopUtils {
Util-Klassen haben einen Privaten Konstruktor. Man soll ja nicht in der Lage sein, da Instanzen draus zu ziehen

2021-07-17 14:14 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/utils/ShopUtils.java
> +                .filter((entity) -> entity instanceof Villager)
```suggestion
                .filter(Villager.class::isInstance)
```

Das wäre eine ordentlichere Lösung

2021-07-17 14:14 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/InvClickListener.java
> +    public void onInvClick(InventoryClickEvent event) {
Ich finde die Methode etwas sehr lang und durcheinander...

Vielleicht kannst du hier diese Sache in mehrere private Methoden aufsplitten um den Code etwas ordentlicher zu machen.

2021-07-17 14:14 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/VillagerClickListener.java
> +public class VillagerClickListener implements Listener {
Ist diese Klasse extra notwendig für die eine Methode?

2021-07-17 14:14 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/VillagerDamageListener.java
> +public class VillagerDamageListener implements Listener {
Auch hier, ist diese Klasse extra notwendig für diese eine Methode?

2021-07-17 14:16 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/InvClickListener.java
> +        if(inventoryName.equalsIgnoreCase(ChatColor.translateAlternateColorCodes('&', "&9Shop | Rush"))
Hab ich bei meinem Review tatsächlich auch angesprochen! Kannst jetzt sogar entscheiden, String#startsWith ist auch eine saubere Methode.

2021-07-17 14:17 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/listeners/InvClickListener.java
> +        if(inventoryName.equalsIgnoreCase(ChatColor.translateAlternateColorCodes('&', "&9Shop | Rush"))
ich find das mit dem regex besser

2021-07-17 16:25 UTC, Sether701 requested changes

2021-07-17 16:25 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/listeners/ShopListener.java
> +    private void switchIntevoryTab(Player player, String displayName) {
rechtschreibfehler in "switchIntevoryTab". Richtig wäre "switchInventoryTab"

2021-07-17 16:25 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/listeners/ShopListener.java
> +
würde sich anbieten ab hier (zeile 46) den Kaufprozess aus dem EventHandler auszulagern, wie du es auch beim switchInventoryTab gemacht hast. Dann wäre der EventHandler hier n bissl ordentlicher

2021-07-17 16:32 UTC, Timeout-Timo approved these changes

2021-07-17 16:32 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/ShopListener.java
> +            switchIntevoryTab(player, clickedItem.getItemMeta().getDisplayName());
Kleiner Faux-Pas in Sachen Rechtschreibung xD
switchInventoryTab müsste es eigentlich heißen

2021-07-18 17:46 UTC, Sether701 approved these changes
passt

2021-07-18 17:47 UTC, Timeout-Timo requested changes

2021-07-18 17:47 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/ShopListener.java
> +            event.setCancelled(true);
Unnötiges cancel. Du cancelst schon in Zeiile 41

2021-07-18 17:47 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/ShopListener.java
> +            if(price > money) {
Das kannst du noch in die Buy-Methode vollständigkeitshalber verschieben

2021-07-18 17:47 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/listeners/ShopListener.java
> +            if(price > money) {
Generell alles ab der Zeile könnte in die Buy-Methode verschoben werden

2021-07-18 18:16 UTC, Timeout-Timo approved these changes

2021-07-18 18:47 UTC, Timeout-Timo commented
Schieb die oben genannten Sachen noch in die Buy-Methode, dann merge ich

2021-07-19 08:21 UTC, Timeout-Timo approved these changes
Kannst eventuell wenn du Zeit findest noch einen Kaufvorgang testen oder so. Passt soweit aber alles, vielleicht kannst du sogar die Variablen price und currency dort aufrufen, wo es nötig ist (Buy-Methode) als schon im Listener. Merge ich so aber trotzdem!

2021-07-19 11:34 UTC, merged