BW-49: Stats Shields will be updated after inagame Phase and bevore lobby phase
Rytrox/Bedwars pull request #41
Opened 2022-01-03 14:51 UTC by Asedem

2022-01-03 14:57 UTC, Sether701 commented
Die Dinger heißen Signs (Shields sind die Dinger, mit denen du Angriffe abwehrst)

2022-01-03 14:58 UTC, Sether701 approved these changes

2022-01-03 15:15 UTC, Timeout-Timo requested changes

2022-01-03 15:15 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/phase/phases/IngamePhase.java
> +        new TopTenBoardHandler();
Was versuchst du hier?

Wenn du willst, dass sich das in jeder Phase aktualisiert, dann registrier den Handler in der Main und schreib nen Listener, der auf das PhaseChangeEvent reagiert...

2022-01-03 15:16 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/phase/phases/IngamePhase.java
> +        new TopTenBoardHandler();
Ansonsten initialisier den TopTenHandler in der Lobbyphase, übergib ihn in die IngamePhase mit und ruf die Update-Methode dort im onDisable auf

2022-01-04 17:22 UTC, Timeout-Timo requested changes

2022-01-04 17:22 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/phase/phases/IngamePhase.java
> +import de.rytrox.bedwars.utils.TopTenBoardHandler;
Der Import kann weg, oder?

2022-01-04 17:28 UTC, Sether701 approved these changes

2022-01-04 17:29 UTC, Sether701 commented
Merge Konflikte noch lösen @Asedem

2022-01-04 18:23 UTC, Timeout-Timo approved these changes

2022-01-04 18:24 UTC, merged