BW-53 Team Anzeige im Scoreboard erstellen und updaten
Rytrox/Bedwars pull request #43
Opened 2022-01-03 18:13 UTC by Asedem

2022-01-03 18:17 UTC, Timeout-Timo requested changes

2022-01-03 18:17 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/utils/Messages.java
> +                                .replace("%alive%", "" + players) :
Es gibt hier doch auch den tollen Haken als Gegenstück zum Kreuz

2022-01-03 18:17 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/utils/ScoreboardManager.java
> +                            .count()))).setScore(score.get());
Warum muss das zum int gecastet werden? Returnt count keinen Integer?

2022-01-03 18:20 UTC, Asedem commented on src/main/java/de/rytrox/bedwars/utils/ScoreboardManager.java
> +                            .count()))).setScore(score.get());
count returnt einen long

2022-01-03 18:22 UTC, Asedem commented on src/main/java/de/rytrox/bedwars/utils/Messages.java
> +                                .replace("%alive%", "" + players) :
![grafik](https://user-images.githubusercontent.com/79838806/147965464-775d2fe9-f8a2-4c9e-a8c2-1c57776655f4.png)
Das sind die beiden Symbole in Minecraft

2022-01-03 18:23 UTC, Sether701 requested changes

2022-01-03 18:23 UTC, Sether701 commented on src/main/java/de/rytrox/bedwars/utils/Messages.java
> +        return isAlive ?
statt isAlive wäre hier canRespawn/hasBed oder so sinnvoller, oder nicht? Weil das ist doch vermutlich auch letztlich das, was hier übergeben wird, oder?

2022-01-03 18:29 UTC, Timeout-Timo approved these changes

2022-01-04 17:21 UTC, Sether701 approved these changes

2022-01-04 17:21 UTC, merged