BW-54: The value of the spawner speed is now saved in the config
Rytrox/Bedwars pull request #46
Opened 2022-01-04 17:44 UTC by Asedem

2022-01-04 17:45 UTC, Sether701 approved these changes

2022-01-04 17:57 UTC, Timeout-Timo requested changes

2022-01-04 17:57 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/database/enums/SpawnerMaterial.java
> +    }
Entweder machst du hier returns zu primitiven Datentypen oder addest hier überall NotNull

2022-01-09 11:49 UTC, Timeout-Timo approved these changes

2022-01-09 11:49 UTC, merged