BW-34 Inventar clearen bei Leave
Rytrox/Bedwars pull request #48
Opened 2022-01-04 18:07 UTC by kaigoe

2022-01-04 18:23 UTC, Timeout-Timo requested changes
Ist das ein Scherz 😂 ?

2022-01-04 19:23 UTC, Sether701 commented
lol

2022-01-05 12:04 UTC, kaigoe commented
hä lol wie hab ich das denn geschafft xD

2022-01-05 13:30 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/Bedwars.java
> +        this.playerLeftListener = new PlayerLeftListener();
Also zwischenspeichern musst du den nicht, es reicht, wenn du in der RegisterListener-Methode dort ein new aufrufst. Oder brauchst du den Listener sonst noch irgendwo anders?

2022-01-06 12:34 UTC, Timeout-Timo commented
Bitte Merge-Conflict hier beheben

2022-01-07 08:54 UTC, Timeout-Timo approved these changes

2022-01-07 08:54 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/Bedwars.java
> +    private PlayerLeftListener playerLeftListener;
```suggestion
```

2022-01-07 09:05 UTC, Sether701 approved these changes

2022-01-07 09:05 UTC, merged