BW-55: Checks if a team is empty and removes it and let the last standing team win
Rytrox/Bedwars pull request #49
Opened 2022-01-04 18:51 UTC by Asedem

2022-01-04 19:12 UTC, Timeout-Timo requested changes
Überall wo die die Methode aufrufst, macht das irgendwie keinen wirklichen Sinn...

Es ist ja nur interessant zu wissen, wenn ein Spieler ausscheidet, oder nicht?
Vielleicht sollten wir hier den Countdown in der Lobby anhalten, wenn nicht mindestens zwei Teams mindestens einen Spieler haben

2022-01-10 07:58 UTC, Timeout-Timo approved these changes

2022-01-10 07:58 UTC, Timeout-Timo commented on src/main/java/de/rytrox/bedwars/database/entity/Map.java
> +    public List<Team> getAliveTeams() {
```suggestion
    @NotNull
    public List<Team> getAliveTeams() {
```

2022-01-10 18:22 UTC, Timeout-Timo approved these changes

2022-01-11 17:03 UTC, Sether701 approved these changes

2022-01-11 17:28 UTC, merged